[supervisord]
nodaemon=false
loglevel=info
user=trader
logfile=/dev/stdout
logfile_maxbytes=0

[program:x11vnc]
command=./x11vnc.sh
directory=/home/trader
autostart=true
autorestart=true
autorestart_delay=5
startretries=10
healthcheck_enabled=false

[program:ib-gateway]
command=./gatewaystart.sh -inline
directory=/opt/ibc
environment=DISPLAY=:0
autostart=true
autorestart=true
autorestart_delay=5
startretries=10
healthcheck_enabled=false
